/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.14.v202310241605.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
#ifndef V0_COMMONAPI_Speed_Sensor_STUB_DEFAULT_HPP_
#define V0_COMMONAPI_Speed_Sensor_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/commonapi/SpeedSensorStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace commonapi {

/**
 * Provides a default implementation for SpeedSensorStubRemoteEvent and
 * SpeedSensorStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SpeedSensorStubDefault
    : public virtual SpeedSensorStub {
public:
    COMMONAPI_EXPORT SpeedSensorStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SpeedSensor::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SpeedSensorStubRemoteEvent* initStubAdapter(const std::shared_ptr< SpeedSensorStubAdapter> &_adapter) {
        CommonAPI::Stub<SpeedSensorStubAdapter, SpeedSensorStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    COMMONAPI_EXPORT virtual const uint32_t &getSpeedAttribute() {
        return speedAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getSpeedAttribute();
    }
    COMMONAPI_EXPORT virtual void setSpeedAttribute(uint32_t _value) {
        const bool valueChanged = trySetSpeedAttribute(std::move(_value));
        if (valueChanged) {
            fireSpeedAttributeChanged(speedAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value) {
        (void)_client;
        setSpeedAttribute(_value);
    }
    COMMONAPI_EXPORT virtual const uint32_t &getRpmfAttribute() {
        return rpmfAttributeValue_;
    }
    COMMONAPI_EXPORT virtual const uint32_t &getRpmfAttribute(const std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return getRpmfAttribute();
    }
    COMMONAPI_EXPORT virtual void setRpmfAttribute(uint32_t _value) {
        const bool valueChanged = trySetRpmfAttribute(std::move(_value));
        if (valueChanged) {
            fireRpmfAttributeChanged(rpmfAttributeValue_);
        }
    }
    COMMONAPI_EXPORT virtual void setRpmfAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value) {
        (void)_client;
        setRpmfAttribute(_value);
    }


protected:
    COMMONAPI_EXPORT virtual bool trySetSpeedAttribute(uint32_t _value) {
        if (!validateSpeedAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<SpeedSensorStubAdapter> stubAdapter = CommonAPI::Stub<SpeedSensorStubAdapter, SpeedSensorStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockSpeedAttribute(true);
            valueChanged = (speedAttributeValue_ != _value);
            speedAttributeValue_ = std::move(_value);
            stubAdapter->lockSpeedAttribute(false);
        } else {
            valueChanged = (speedAttributeValue_ != _value);
            speedAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateSpeedAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteSpeedAttributeChanged() {
        // No operation in default
    }
    COMMONAPI_EXPORT virtual bool trySetRpmfAttribute(uint32_t _value) {
        if (!validateRpmfAttributeRequestedValue(_value))
            return false;

        bool valueChanged;
        std::shared_ptr<SpeedSensorStubAdapter> stubAdapter = CommonAPI::Stub<SpeedSensorStubAdapter, SpeedSensorStubRemoteEvent>::stubAdapter_.lock();
        if(stubAdapter) {
            stubAdapter->lockRpmfAttribute(true);
            valueChanged = (rpmfAttributeValue_ != _value);
            rpmfAttributeValue_ = std::move(_value);
            stubAdapter->lockRpmfAttribute(false);
        } else {
            valueChanged = (rpmfAttributeValue_ != _value);
            rpmfAttributeValue_ = std::move(_value);
        }

       return valueChanged;
    }
    COMMONAPI_EXPORT virtual bool validateRpmfAttributeRequestedValue(const uint32_t &_value) {
        (void)_value;
        return true;
    }
    COMMONAPI_EXPORT virtual void onRemoteRpmfAttributeChanged() {
        // No operation in default
    }
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SpeedSensorStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SpeedSensorStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }

        COMMONAPI_EXPORT virtual void onRemoteSpeedAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteSpeedAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetSpeedAttribute(uint32_t _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetSpeedAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetSpeedAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value) {
            (void)_client;
            return onRemoteSetSpeedAttribute(_value);
        }
        COMMONAPI_EXPORT virtual void onRemoteRpmfAttributeChanged() {
            assert(defaultStub_ !=NULL);
            defaultStub_->onRemoteRpmfAttributeChanged();
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetRpmfAttribute(uint32_t _value) {
            assert(defaultStub_ !=NULL);
            return defaultStub_->trySetRpmfAttribute(std::move(_value));
        }

        COMMONAPI_EXPORT virtual bool onRemoteSetRpmfAttribute(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _value) {
            (void)_client;
            return onRemoteSetRpmfAttribute(_value);
        }

    private:
        SpeedSensorStubDefault *defaultStub_;
    };
protected:
    SpeedSensorStubDefault::RemoteEventHandler remoteEventHandler_;

private:

    uint32_t speedAttributeValue_ {};
    uint32_t rpmfAttributeValue_ {};

    CommonAPI::Version interfaceVersion_;
};

} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_Speed_Sensor_STUB_DEFAULT
